### ISSUE TITLE
Error: Gulp build

### ISSUE THREAD

**Issue by eidmanna** [mormegil-cz/stackflame#1]
Hi,
I am trying to build you project with gulp.
After a git clone I do 'npm install' und then 'gulp'

I have this error ... any ideas?

$ gulp
[12:53:19] Using gulpfile ~\Documents\development\stackflame\gulpfile.js
[12:53:19] Starting 'default'...
[12:53:19] Starting 'copy-html'...
[12:53:19] Starting 'copy-css'...
[12:53:19] Starting 'copy-js'...
[12:53:19] Finished 'copy-html' after 20 ms
[12:53:19] Finished 'copy-css' after 22 ms
[12:53:19] Finished 'copy-js' after 24 ms
[12:53:19] Starting 'bundle'...
[12:53:20] [SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'] {
  line: 1,
  column: 1,
  annotated: '\n' +
    'C:\\Users\\eidmaa\\Documents\\development\\stackflame\\node_modules\\d3-flame-graph\\index.js:1\n' +
    "export { default as flamegraph } from './dist/d3-flamegraph.js'\n" +
    '^\n' +
    "ParseError: 'import' and 'export' may appear only with 'sourceType: module'",
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      finish: [Function],
      error: [Function (anonymous)],
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 1,
      writing: true,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: [Function: nop],
      writelen: 1,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [DestroyableTransform] ],
    length: 1,
    label: 'syntax',
    [Symbol(kCapture)]: false
  }
}

**Comment by mormegil-cz** [comment]
You are right, a clean installation stopped working because of some package update; I don’t have the patience to try and find the specific problematic package, so I committed the package lock file which works for me (which is correct, anyway).

I hate the JS ecosystem and tooling, always breaking by itself…

Try if it helped.

**Comment by eidmanna** [comment]
Thank you. Now every thing builds fine :-). This is the reason, why they invented the package lock file ;-). And thank you for providing this tool in github. It is very helpful for analyzing threaddumps.
